import React, { FC } from 'react'
import { Russo_One } from '@next/font/google'
import Footer from '../components/Footer/Footer'
import Header from '../components/Header/Header'
import Head from 'next/head'
const RussoOne = Russo_One({
	weight: '400',
	subsets: ['latin', 'cyrillic'],
})
const Layout: FC<{ children: React.ReactNode }> = ({ children }) => {
	return (
		<>
			<Head>
				<title>Kaze shop</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
				<link rel='preconnect' href='https://fonts.googleapis.com' />
				<link rel='preconnect' href='https://fonts.gstatic.com' />
				<link
					href='https://fonts.googleapis.com/css2?family=Russo+One&display=swap'
					rel='stylesheet'
				/>
				<link
					href='https://fonts.googleapis.com/css2?family=Georama:wght@300;400&display=swap'
					rel='stylesheet'
				></link>
			</Head>
			
			<div className='wrapper'>
				<Header />
				{children}
				{/* <Footer /> */}
			</div>
		</>
	)
}

export default Layout
